# Copyright 2018 Stanford University see Apache2.txt for license
# Node.js Javascript CircleCI 2.0 configuration file
#
# Check https://hub.docker.com/r/circleci/node/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/node:10.11-browsers
  working_directory: ~/sinopia_editor

version: 2
jobs:
  # Maintains cache of 2 sets of node_modules: production and CI
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-prod-{{ checksum "package.json" }}
      - run: npm install --only=production
      - save_cache:
          key: dependencies-prod-{{ checksum "package.json" }}
          paths:
            - node_modules
      - restore_cache:
          key: dependencies-ci-{{ checksum "package.json" }}
      - run: npm install # including CI/Test dependencies
      - save_cache:
          key: dependencies-ci-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependencies-ci-{{ checksum "package.json" }}
      - run: npm run eslint
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - run:
          command: npm run jest-ci
          environment:
            JEST_JUNIT_OUTPUT: "test-results/jest/jest-results.xml"

  register_image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache: # gives us back matching node_modules
          key: dependencies-prod-{{ checksum "package.json" }}
      - attach_workspace:
          at: .
      - run:
          name: Build & Register Image
          command: |
            docker build -t ld4p/sinopia_editor:latest .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ld4p/sinopia_editor:latest

workflows:
  version: 2
  build:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - register_image:
          requires:
            - build
          filters:
            branches:
              only:
                - master
