# Node.js Javascript CircleCI 2.0 configuration file
#
# Check https://hub.docker.com/r/circleci/node/ for more details
#
defaults: &defaults
  docker:
    - image: circleci/node:10.11-browsers
  working_directory: ~/sinopia_editor

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run eslint
      - run: npm run grunt
      - run:
          command: npm run jest-ci
          environment:
            JEST_JUNIT_OUTPUT: "test-results/jest/jest-results.xml"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
          destination: jest-coverage
      - run: npm run analysis
      - store_artifacts:
          path: static-analysis
          destination: static-analysis

workflows:
  version: 2
  build:
    jobs:
      - build
